@API_psi_spolky_HostAddress = http://localhost:5110

### Register a new user
POST {{API_psi_spolky_HostAddress}}/register
Content-Type: application/json
Accept: application/json

{
  "email": "cykablyat@gmail.com",
  "password": "Cyka blyat666!!",
  "name": "Stevek",
  "surname": "11",
  "role": "Admin",
  "phoneNumber": "123456789"
}

### Login with the user's credentials
POST {{API_psi_spolky_HostAddress}}/login
Content-Type: application/json
Accept: application/json

{
  "userName": "Stevek",
  "password": "Cyka blyat666!!"
}
### Get this logged in user user
GET {{API_psi_spolky_HostAddress}}/me
###
POST   {{API_psi_spolky_HostAddress}}/logout
Content-Type: application/json
Accept: application/json